# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts "Destroy all shops"

Shop.destroy_all

puts "Destroy all collections"

Collection.destroy_all

puts "Destroy all users"

User.destroy_all

puts "Destroy all Video Games"

VideoGame.destroy_all

puts "Create Users"

User.create!(first_name: "Pierre", last_name: "Quiroule", username: "Plouf", email: "papapa@gmail.com", password:"papapa")

puts "Create Video Games"

VideoGame.create!(title:"Super Mario Kart", platform:"Game Boy Advance", category:"Good old times", editor:"Inteligent Systems", year: "2003", description:"Mario Kart: Super Circuit is a 2003 kart racing video game developed by Intelligent Systems and published by Nintendo for the Game Boy Advance. The game is the third installment in the Mario Kart series and the first for handhelds, following Super Mario Kart (1992) and Mario Kart 64 (1996). Super Circuit is a kart racing video game in which the player races in a kart against other teams in different courses. The game screen indicates the current standings in a race, the number of laps needed to finish and incoming weapons. Like in the previous installments, players can pick up item boxes to receive a randomly selected item and use it to impede the opposition and gain the advantage. Some items, such as shells and banana peels, allow the player to hit others to slow them down, while other items, such as the star power-up, render them temporarily invincible to attacks. This is the second Mario Kart game to include coins, which increases the engine power of the karts.")
VideoGame.create!(title:"Age of Empires II: The Age of Kings", platform:"PC", category:"Good old times", editor:"Ensemble Studios", year: "2000", description:"Age of Empires II: The Age of Kings is a real-time strategy video game developed by Ensemble Studios and published by Microsoft. Released in 1999 for Microsoft Windows and Macintosh, it is the second game in the Age of Empires series. The Age of Kings is set in the Middle Ages and contains thirteen playable civilizations. Players aim to gather resources, which they use to build towns, create armies, and defeat their enemies. There are five historically based campaigns, which constrict the player to specialized and story-backed conditions.")
VideoGame.create!(title:"Black", platform:"PlayStation 2", category:"Infiltration", editor:"Criterion Games", year: "1992", description:"Black is a first-person shooter video game developed by Criterion Games and published by Electronic Arts. It was released for the PlayStation 2 and Xbox in February 2006. The player assumes control of Jack Kellar, a black ops agent being interrogated about his previous missions involving a terrorist operation. Played from a first-person perspective, players confront enemies using firearms and grenades. The game is notable for its heavily stylized cinema-inspired action as well as its sound quality and focus on destructive effects during gameplay.")
VideoGame.create!(title:"Ico", platform:"PlayStation 2", category:"Aesthetic", editor:"Japan Studio", year: "1999", description:"Ico is an action-adventure game developed by Japan Studio and Team Ico, and published by Sony Computer Entertainment, released for the PlayStation 2 video game console in 2001 and 2002 in various regions. It was designed and directed by Fumito Ueda, who wanted to create a minimalist game around a boy meets girl concept. Originally planned for the PlayStation, Ico took approximately four years to develop. The team employed a subtracting design approach to reduce elements of gameplay that interfered with the game's setting and story in order to create a high level of immersion.")
VideoGame.create!(title:"Shadow of the Colossus", platform:"PlayStation 2", category:"Aesthetic", editor:"Japan Studio", year: "1996", description:"The game's storyline focuses on a young man named Wander who enters a forbidden land. Wander must travel across a vast expanse on horseback and defeat sixteen massive beings, known simply as colossi, in order to restore the life of a girl named Mono. The game is unusual within the action-adventure genre in that there are no towns or dungeons to explore, no characters with whom to interact, and no enemies to defeat other than the colossi.")
VideoGame.create!(title:"Dune 2000", platform:"PC", category:"My favorite strategy", editor:"Intelligent Games", year: "1998", description:"Emperor Corrino (Adrian Sparks) has issued a challenge that the House which can produce the most spice will control its source, the desert planet Dune, with no rules as to how the Houses can achieve the goal. Meanwhile, Lady Elara (Musetta Vander) of the Bene Gesserit and bound concubine to the Emperor, secretly takes the commander - the player - into one of the Heighliners, a person whose bloodline and future the Sisterhood had checked.")
VideoGame.create!(title:"Age of Empires III", platform:"PC", category:"My favorite strategy", editor:"Ensemble Studios", year: "2005", description:"Age of Empires III is a real-time strategy video game developed by Microsoft Corporation's Ensemble Studios and published by Microsoft Game Studios. The Mac version was ported over and developed and published by Destineer's MacSoft.")
VideoGame.create!(title:"Age of Empires", platform:"PC", category:"Good old times", editor:"Ensemble Studios", year: "1998", description:"Age of Empires (AoE) is a history-based real-time strategy video game developed by Ensemble Studios and published by Microsoft, and the first game in the Age of Empires series. The game uses the Genie Engine, a 2D sprite-based game engine. The game allows the user to act as the leader of an ancient civilization by advancing it through four ages (the Stone, Tool, Bronze, and Iron Ages), gaining access to new and improved units with each advance.")
VideoGame.create!(title:"Civilization II", platform:"PC", category:"Good old times", editor:"MicroProse", year: "1996", description:"Sid Meier's Civilization II is a turn-based strategy video game in the Civilization series, developed and published by MicroProse. It was released in 1996 for PCs and later ported to the PlayStation by Activision.")
VideoGame.create!(title:"Civilization", platform:"PC", category:"Good old times", editor:"MicroProse", year: "1991", description:"Sid Meier's Civilization is a 1991 turn-based strategy 4X video game developed and published by MicroProse. The game was originally developed for MS-DOS running on a PC, and has undergone numerous revisions for various platforms. The player is tasked with leading an entire human civilization over the course of several millennia by controlling various areas such as urban development, exploration, government, trade, research, and military. The player can control individual units and advance the exploration, conquest and settlement of the game's world. The player can also make such decisions as setting forms of government, tax rates and research priorities. The player's civilization is in competition with other computer-controlled civilizations, with which the player can enter diplomatic relationships that can either end in alliances or lead to war.")
VideoGame.create!(title:"Myst III: Exile", platform:"PC", category:"Boring", editor:"Presto Studios", year: "2002", description:"Myst III: Exile is the third title in the Myst series of graphic adventure puzzle video games. While the preceding games in the series, Myst and Riven, were produced by Cyan Worlds and published by Brøderbund, Exile was developed by Presto Studios and published by Ubi Soft. The game was released on four compact discs for both Mac OS and Microsoft Windows on May 8, 2001; versions for the Xbox and PlayStation 2 were released in late 2002. A single-disc DVD version was later released for Windows and Mac OS.")
VideoGame.create!(title:"Myst IV: Revelation", platform:"PC", category:"Boring", editor:"Ubisoft Montreal", year: "2004", description:"Myst IV: Revelation is an adventure video game, the fourth installment in the Myst series, developed and published by Ubisoft. Like Myst III: Exile, Revelation combines pre-rendered graphics with digital video, but also features real-time 3D effects for added realism. The plot of Revelation follows up on plot details from the original Myst. The player is summoned by Atrus, a man who creates links to other worlds known as Ages by writing special linking books. Almost twenty years earlier, Atrus' two sons nearly destroyed all of his books and were imprisoned; Atrus now wishes to see if his sons' imprisonment has reformed them. The player travels to each brother's prison, in an attempt to recover Atrus' daughter Yeesha from the brothers' plot.")
VideoGame.create!(title:"Return to Castle Wolfenstein", platform:"PC", category:"History", editor:"Gray Matter Interactive", year: "2001", description:"Return to Castle Wolfenstein is a first-person shooter video game published by Activision, released on November 19, 2001 for Microsoft Windows and subsequently for PlayStation 2, Xbox, Linux and Macintosh. The game serves as both a remake and a reboot to the Wolfenstein series.")
VideoGame.create!(title:"Half-Life", platform:"PC", category:"Fav", editor:"Valve", year: "1998", description:"Half-Life is a first-person shooter video game developed by Valve and published by Sierra Studios for Microsoft Windows in 1998. It was Valve's debut product and the first game in the Half-Life series. Players assume the role of Gordon Freeman, a scientist who must escape the Black Mesa Research Facility after it is invaded by aliens. The core gameplay consists of fighting alien and human enemies with a variety of weapons and solving puzzles.")
VideoGame.create!(title:"Half-Life 2", platform:"Xbox", category:"Good old times", editor:"Valve", year: "2004", description:"Half-Life 2 is a 2004 first-person shooter game developed and published by Valve. Like the original Half-Life (1998), it combines shooting, puzzles, and storytelling, and adds features such as vehicles and physics-based gameplay. Players control Gordon Freeman, who fights the alien Combine with allies including resistance fighter Alyx Vance, using weapons such as the object-manipulating gravity gun.")
VideoGame.create!(title:"RollerCoaster Tycoon", platform:"PC", category:"My favorite strategy", editor:"Chris Sawyer Productions", year: "1999", description:"RollerCoaster Tycoon is a 1999 construction and management simulation video game themed around amusement parks. Developed by Chris Sawyer Productions and published by Hasbro Interactive.")
VideoGame.create!(title:"The Legend of Zelda: Phantom Hourglass", platform:"Nintendo DS", category:"Boring", editor:"Nintendo EAD", year: "2007", description:"The Legend of Zelda: Phantom Hourglass is an action-adventure game with gameplay similar to other games in The Legend of Zelda series. The player controls Link, the protagonist, and explores the world to find new items, information, and allies to help him save his friend Tetra and defeat the antagonist Bellum. The game is divided into two gameplay types: sailing between islands, and exploring the islands and their dungeons on foot.")
VideoGame.create!(title:"SimCity 3000", platform:"PC", category:"Boring", editor:"Maxis", year: "1999", description:"There are many changes between SimCity 3000 and its immediate predecessor SimCity 2000. These changes span both the integral city management aspects of the game, as well as its graphical and landscape aspects. More and newer city services are featured. These changes create a greatly different experience from that of SimCity 2000.")
VideoGame.create!(title:"SimCity 2000", platform:"PC", category:"Good old times", editor:"Maxis", year: "1993", description:"SimCity 2000 is a city-building simulation video game jointly developed by Will Wright and Fred Haslam of Maxis. It is the successor to SimCity Classic and was released for Apple Macintosh personal computers in 1993, after which it was released on other platforms over the following years, such as the Sega Saturn and SNES game consoles in 1995 and the PlayStation in 1996.")
VideoGame.create!(title:"Pikmin", platform:"GameCube", category:"Fav", editor:"Nintendo EAD", year: "2001", description:"Pikmin is a real-time strategy and puzzle video game series created by Shigeru Miyamoto and published by Nintendo. The games focus on directing a horde of plant-like creatures called Pikmin in order to collect items by destroying obstacles, avoiding hazards and fighting fauna that are hazardous to both the player character and the Pikmin.")
VideoGame.create!(title:"The Legend of Zelda: Twilight Princess", platform:"Wii", category:"Fav", editor:"Nintendo EAD", year: "2006", description:"The Legend of Zelda: Twilight Princess is an action-adventure game developed and published by Nintendo for the GameCube and Wii home video game consoles. It is the thirteenth installment in the series The Legend of Zelda.")

puts "Create Shops"

Shop.create!(name: "Game", address: "74, Rue Faidherbe, 59800 Lille")
Shop.create!(name: "Micromania", address: "51 Avenue Willy Brandt, 59000 Lille")
Shop.create!(name: "Micromania", address: "52 Rue de Béthune, 59800 Lille")
Shop.create!(name: "Micromania", address: "130 Rue du Grand But Lomme, 59160 Lille")
Shop.create!(name: "Micromania", address: "46 Avenue de l'Avenir, 59650 Villeneuve-d'Ascq")

puts "Finished !"
